export const cardArray = [
  {
    id: 0,
    title: "Пвх материал 0й сорт",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
  {
    id: 1,
    title: "Пвх материал 1й сорт",
    price: "180 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
  {
    id: 2,
    title: "Пвх материал 2й сорт",
    price: "190 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
  {
    id: 3,
    title: "Пвх материал 3й сорт",
    price: "200 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
  {
    id: 4,
    title: "Пвх материал 4й сорт",
    price: "210 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
  {
    id: 5,
    title: "Пвх материал 5й сорт",
    price: "220 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-img.png",
  },
];
